#define SPI_DDR DDRA
#define SPI_MISO PINA0

#define DDR DDRA
#define PORT PORTA
#define PIN PINA
#define INCOMING_CALL_PIN PINA6
#define HOOK_MODE_PIN PINA7
#define WAIT_MODE_PIN PINA4
#define OPEN_PIN PINA5